default:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: hive_metastore
      schema: jasper
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "sql/protocolv1/o/{{ env_var('DBT_ORG_ID') }}/{{ env_var('DBT_CLUSTER_ID') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 4
